### ISSUE TITLE
Some issues with style

### ISSUE THREAD

**Issue by abkrim** [hamed-ehtesham/pretty-checkbox-vue#1]
Hi. After try use on my own project get a issue with css style.

I don't know how to correct or what is origing of mistake.

I use with boostrap theme material.

I try with embebed on my style using **dl**  **dt**  and also only with  **div**

![prettycheck-fail_style](https://user-images.githubusercontent.com/1238625/34983828-19031fb8-faaf-11e7-87fa-e8ece40e0af0.jpg)

If you like see on [develop site](https://lowino.es/),

**Comment by hamed-ehtesham** [comment]
Hi,
First of all thank you for using "pretty-checkbox"
Then i should say this problem is not related to this component but "pretty-checkbox" itself and it should be issued [here](https://github.com/lokesh-coder/pretty-checkbox/issues)
The problem is your app tries to style pretty checkbox inputs from 2 different sources: "pretty-checkbox" and "bootstrap material theme" which is not gonna lead to a proper style for your pretty checkbox inputs and that is not an issue from "pretty checkbox"
In general, some libraries/frameworks have global influence on your application which is not good in my opinion. as in this case "bootstrap material theme" changes the style of all inputs no matter if that input is using another library/framework or not.
As for now i can suggest you to use libraries/frameworks which doesn't affect your whole application such as "bootstrap", "bulma" and "pretty-checkbox"

i will let you know if i find a way to use "pretty-checkbox" alongside "bootstrap material theme"

**Comment by abkrim** [comment]
Lol. There're a lot of components, and all work fine with "others" libraries/frameworks.... best way for me it's not use pretty-checkbox. Thanks for your efforts.

**Comment by lokesh-coder** [comment]
Hi @abkrim ,

Try this css,

```css
.pretty input[type=radio] {
    position: absolute;
}
```

**Comment by abkrim** [comment]
A lot of thanks @lokesh-coder work fine. I need more experience on CSS. I put o my own sass, transpiling and work
